package core;

/**
 * Created by Karlos on 1/28/2016.
 */
public enum Token {
    ASSIGN,RESERVADA_PUBLIC,RESERVADA_VOID,RESERVADA_MAIN,RESERVADA_FUNTION,RESERVADA_STRING,RESERVADA_PRIVATE,RESERVADA_VAR,OPENKEY,CLOSEKEY,EQUALS,IDENTIFICADOR,INT,FLOAT,PLUS,TIMES,MINUS,ERROR,STRING;
}
